version: '3.4'

services:
  zabbix-server:
    image: evoluservicesbr/zabbix-server:3.0
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: "evcash-sandbox-cluster.cluster-ro-cqxaz503ktgi.us-west-2.rds.amazonaws.com"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbixdb"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "YhttziACM4f3"
      ZBX_DEBUGLEVEL: 1
      ZBX_STARTPOLLERS: 20
      ZBX_IPMIPOLLERS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 12
      ZBX_STARTTRAPPERS: 8
      ZBX_STARTPINGERS: 5
      ZBX_STARTDISCOVERERS: 5
      ZBX_STARTHTTPPOLLERS: 5
      ZBX_STARTJAVAPOLLERS: 5
      ZBX_HOUSEKEEPINGFREQUENCY: 24
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      ZBX_CACHESIZE: 8M
      ZBX_HISTORYCACHESIZE: 16M
      ZBX_HISTORYINDEXCACHESIZE: 4M
    labels:
      - "traefik.enable=false"
    volumes:
      - /app/docker/zabbix2/data-zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /app/docker/zabbix2/data-zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - /app/docker/zabbix2/data-zabbix/modules:/var/lib/zabbix/modules
      - /app/docker/zabbix2/data-zabbix/enc:/var/lib/zabbix/enc
    networks:
      - zabbix2_default
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-4.2.4
    environment:
      DB_SERVER_HOST: "evcash-sandbox-cluster.cluster-ro-cqxaz503ktgi.us-west-2.rds.amazonaws.com"
      DB_SERVER_PORT: "3306"
      MYSQL_DATABASE: "zabbixdb"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "YhttziACM4f3"
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "America/Fortaleza"
      ZBX_MAXEXECUTIONTIME: 500
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.docker.network=zabbix2_default"
      - "traefik.frontend.rule=Host:zabbix.evoluservices.com"
      - "traefik.backend=zabbix-web"
      - "traefik.weight=0"
    depends_on:
      - zabbix-server
    networks:
      - zabbix2_default
networks:
  zabbix2_default:
    external: true