---
- name: install Python e agent zabbix
  apt:
    name: ['python3', 'python-pip']
    update_cache: yes
    state: present
  when: (ansible_os_family == "Debian") or (ansible_os_family == "Ubuntu")

- name: instalando zabbix-api
  pip:
    name: zabbix-api