---
- name: Registro de sistema operacional
  shell: lsb_release -si | tr 'A-Z' 'a-z'
  register: SO

- name: Registro da versao do sistema operacional
  shell: lsb_release -sc
  register: SOVERSION

- name: Registro do nome da maquina
  shell: hostname
  register: hname

- name: Registro de pacote instalado
  shell: dpkg -l | grep zabbix-agent; echo $?
  register: ipack

- name: Se não encontrar o download  pelo S3 vai pela internet
  block:
    - debug:
        msg: "Instalacao via S3"

    - name: Removendo bibliotecas Zabbix-Agent
      action: raw dpkg --purge zabbix-release && dpkg --purge zabbix-agent
      when: ipack.stdout != "1"

    - name: Baixando biblioteca Zabbix-Agent 4.0
      action: raw wget https://s3-sa-east-1.amazonaws.com/evoluservices/packages/zabbix/4.0/"{{ SO.stdout }}"/zabbix-release/zabbix-release_4.0-2%2B"{{ SOVERSION.stdout }}"_all.deb

    - name: Executando novos repositorios .deb
      action: raw dpkg -i zabbix-release_4.0-2+"{{ SOVERSION.stdout }}"_all.deb

    - name: Atualizando repositorios
      action: raw apt-get update

    - name: Install agent-zabbix
      apt:
        name: zabbix-agent
        state: present

  rescue:
    - debug:
        msg: "instalação pela internet"

    - name: Baixando biblioteca Zabbix-Agent 4.0
      action: raw wget http://repo.zabbix.com/zabbix/4.0/"{{ SO.stdout }}"/pool/main/z/zabbix-release/zabbix-release_4.0-2%2B"{{ SOVERSION.stdout }}"_all.deb

    - name: Executando novos repositorios .deb
      action: raw dpkg -i zabbix-release_4.0-2+"{{ SOVERSION.stdout }}"_all.deb

    - name: Atualizando repositorios
      action: raw apt-get update

    - name: Install agent-zabbix
      apt:
        name: zabbix-agent
        state: present

- name: conf corp
  copy:
    src: zabbix/agent-conf-corp/zabbix_agentd.conf
    dest: /etc/zabbix/
  when:
    - CONF == "CORP"

- name: conf dmz
  copy:
    src: zabbix/agent-conf-dmz/zabbix_agentd.conf
    dest: /etc/zabbix/
  when:
    - CONF == "DMZ"
- name: conf aws
  copy:
    src: zabbix/agent-conf-aws/zabbix_agentd.conf
    dest: /etc/zabbix/
  when:
    - CONF == "AWS"

- name: adicionado nome do host
  action: raw sed -i "s/Hostname=zabbix/Hostname="{{ hname.stdout }}"/g" /etc/zabbix/zabbix_agentd.conf


